# Generated by Django 5.2 on 2025-04-26 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0002_remove_book_cover_image_book_author_book_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='label',
            field=models.CharField(blank=True, choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], max_length=1),
        ),
        migrations.AddField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, choices=[('Hardcover', 'Hardcover'), ('Paperback', 'Paperback'), ('Ebook', 'Ebook')], max_length=20),
        ),
    ]
