# Generated by Django 5.2 on 2025-04-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solo', '0003_book_label_book_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='type',
            field=models.CharField(blank=True, choices=[('New', 'New'), ('Bestseller', 'Bestseller'), ('Offers', 'On offers')], max_length=20),
        ),
    ]
